version: '3'

services:
  perfex:
    image: perfex
    depends_on:
      - mysql
    ports:
      - "888:80"
    volumes:
      - perfex_data:/var/www/html/
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=perfex_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  perfex_data: 
    driver: local
  mysql_data: 
    driver: local